import { useEffect, useState } from 'react';
import { apiRequest } from '../../services/api';
import './dashboard.css';

const statusLabels = { pending: 'Pendiente', preparing: 'En preparación', shipped: 'Listo para entrega', delivered: 'Entregado', cancelled: 'Cancelado' };
const roleLabels = { admin: 'Admin', client: 'Cliente', cook: 'Cocinero', courier: 'Repartidor' };
const transitions = { pending: ['preparing', 'cancelled'], preparing: ['shipped', 'cancelled'], shipped: ['delivered', 'cancelled'] };
const emptyUser = { name: '', email: '', password: '', phone: '', role: 'client', active: true };
const emptyProduct = { name: '', description: '', price: '', category_id: '' };
const emptyCategory = { name: '', description: '' };
const emptyIngredient = { name: '', unit: '', current_stock: '', minimum_stock: '' };
const emptyPromotion = { product_id: '', name: '', discount_percentage: '', start_date: '', end_date: '' };

function Table({ children }) { return <div className="dashboard-table-wrap"><table className="dashboard-table">{children}</table></div>; }
function Actions({ children }) { return <div className="dashboard-actions">{children}</div>; }

export function OrdersDashboard({ mode }) {
  const [orders, setOrders] = useState([]); const [error, setError] = useState(''); const [loadingId, setLoadingId] = useState(null); const isCook = mode === 'cook';
  useEffect(() => { let active = true; apiRequest('/orders').then((data) => { if (active) setOrders(data); }).catch((err) => { if (active) setError(err.message); }); return () => { active = false; }; }, []);
  async function updateStatus(order) { setLoadingId(order.id); try { const status = isCook ? (order.status === 'pending' ? 'preparing' : 'shipped') : 'delivered'; await apiRequest(`/orders/${order.id}/status`, { method: 'PUT', body: JSON.stringify({ status }) }); setOrders(await apiRequest('/orders')); } catch (err) { setError(err.message); } finally { setLoadingId(null); } }
  return <section className="dashboard-page"><div className="dashboard-shell"><div className="dashboard-heading"><div><h1>{isCook ? 'Cocina' : 'Repartos'}</h1><p>{isCook ? 'Pedidos pendientes y en preparación.' : 'Pedidos listos para entregar.'}</p></div></div><div className="dashboard-panel">{error && <p className="dashboard-error">{error}</p>}<Table><thead><tr><th>Pedido</th><th>Cliente</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td>#{order.id}</td><td>{order.user?.name || 'Cliente'}</td><td><span className="status">{statusLabels[order.status] || order.status}</span></td><td><button disabled={loadingId === order.id} onClick={() => updateStatus(order)}>{loadingId === order.id ? 'Actualizando...' : (isCook ? 'Actualizar estado' : 'Marcar entregado')}</button></td></tr>)}</tbody></Table></div></div></section>;
}

async function getAdminData() { return Promise.all([apiRequest('/orders'), apiRequest('/admin/products'), apiRequest('/categories'), apiRequest('/users'), apiRequest('/ingredients'), apiRequest('/admin/promotions'), apiRequest('/payments')]); }

export function AdminDashboard() {
  const [data, setData] = useState({ orders: [], products: [], categories: [], users: [], ingredients: [], promotions: [], payments: [] }); const [error, setError] = useState('');
  async function refresh() { const [orders, products, categories, users, ingredients, promotions, payments] = await getAdminData(); setData({ orders, products, categories, users, ingredients, promotions, payments }); }
  useEffect(() => { let active = true; getAdminData().then(([orders, products, categories, users, ingredients, promotions, payments]) => { if (active) setData({ orders, products, categories, users, ingredients, promotions, payments }); }).catch((err) => { if (active) setError(err.message); }); return () => { active = false; }; }, []);
  const counts = data.orders.reduce((result, order) => ({ ...result, [order.status]: (result[order.status] || 0) + 1 }), {});
  return <section className="dashboard-page"><div className="dashboard-shell"><div className="dashboard-heading"><div><h1>Administración</h1><p>Gestión central de usuarios, catálogo, pedidos y pagos.</p></div></div>{error && <p className="dashboard-error">{error}</p>}<div className="dashboard-grid">{[[data.orders.length, 'Pedidos'], [data.products.length, 'Productos'], [data.users.length, 'Usuarios'], [data.ingredients.length, 'Ingredientes'], [data.promotions.length, 'Promociones'], [data.payments.length, 'Pagos']].map(([value, label]) => <div className="dashboard-stat" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div><section className="dashboard-panel dashboard-section"><h2>Pedidos por estado</h2><Actions>{Object.entries(statusLabels).map(([status, label]) => <span className="status" key={status}>{label}: {counts[status] || 0}</span>)}</Actions></section><div className="dashboard-accordions"><AdminAccordion title="Usuarios y roles" open><UserManagement users={data.users} onRefresh={refresh} onError={setError} /></AdminAccordion><AdminAccordion title="Productos y categorías"><CatalogManagement products={data.products} categories={data.categories} onRefresh={refresh} onError={setError} /></AdminAccordion><AdminAccordion title="Ingredientes"><IngredientManagement ingredients={data.ingredients} onRefresh={refresh} onError={setError} /></AdminAccordion><AdminAccordion title="Promociones"><PromotionManagement promotions={data.promotions} products={data.products} onRefresh={refresh} onError={setError} /></AdminAccordion><AdminAccordion title="Pedidos e historial"><AdminOrderManagement orders={data.orders} onRefresh={refresh} onError={setError} /></AdminAccordion><AdminAccordion title="Pagos registrados"><PaymentManagement payments={data.payments} /></AdminAccordion></div></div></section>;
}

function AdminAccordion({ title, open = false, children }) {
  return <details className="dashboard-accordion" open={open}><summary>{title}</summary><div className="dashboard-accordion__content">{children}</div></details>;
}

function UserManagement({ users, onRefresh, onError }) {
  const [form, setForm] = useState(emptyUser); const [editingId, setEditingId] = useState(null); const reset = () => { setEditingId(null); setForm(emptyUser); };
  async function save(event) { event.preventDefault(); try { const payload = { ...form }; if (!payload.password) delete payload.password; await apiRequest(editingId ? `/users/${editingId}` : '/users', { method: editingId ? 'PUT' : 'POST', body: JSON.stringify(payload) }); reset(); await onRefresh(); } catch (err) { onError(err.message); } }
  async function changeRole(user, role) { try { await apiRequest(`/users/${user.id}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); await onRefresh(); } catch (err) { onError(err.message); } }
  return <section className="dashboard-panel dashboard-section"><h2>Usuarios y roles</h2><form className="dashboard-form dashboard-form--grid" onSubmit={save}><input placeholder="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><input type="email" placeholder="Correo" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><input placeholder="Teléfono" value={form.phone || ''} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input type="password" placeholder={editingId ? 'Nueva contraseña (opcional)' : 'Contraseña'} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required={!editingId} minLength="8" /><select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}>{Object.entries(roleLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><label className="dashboard-checkbox"><input type="checkbox" checked={Boolean(form.active)} onChange={(e) => setForm({ ...form, active: e.target.checked })} /> Usuario activo</label><Actions><button type="submit">{editingId ? 'Guardar usuario' : 'Crear usuario'}</button>{editingId && <button type="button" onClick={reset}>Cancelar</button>}</Actions></form><Table><thead><tr><th>Nombre</th><th>Correo</th><th>Teléfono</th><th>Rol</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>{user.name}</td><td>{user.email}</td><td>{user.phone || 'Sin teléfono'}</td><td><select value={user.role} onChange={(e) => changeRole(user, e.target.value)}>{Object.entries(roleLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></td><td>{user.active ? 'Activo' : 'Inactivo'}</td><td><button type="button" onClick={() => { setEditingId(user.id); setForm({ ...emptyUser, ...user, password: '' }); }}>Editar</button></td></tr>)}</tbody></Table></section>;
}

function CatalogManagement({ products, categories, onRefresh, onError }) {
  const [product, setProduct] = useState(emptyProduct); const [category, setCategory] = useState(emptyCategory); const [productId, setProductId] = useState(null); const [categoryId, setCategoryId] = useState(null);
  async function saveProduct(event) { event.preventDefault(); try { await apiRequest(productId ? `/products/${productId}` : '/products', { method: productId ? 'PUT' : 'POST', body: JSON.stringify({ ...product, price: Number(product.price), category_id: Number(product.category_id) }) }); setProduct(emptyProduct); setProductId(null); await onRefresh(); } catch (err) { onError(err.message); } }
  async function saveCategory(event) { event.preventDefault(); try { await apiRequest(categoryId ? `/categories/${categoryId}` : '/categories', { method: categoryId ? 'PUT' : 'POST', body: JSON.stringify(category) }); setCategory(emptyCategory); setCategoryId(null); await onRefresh(); } catch (err) { onError(err.message); } }
  async function remove(path) { try { await apiRequest(path, { method: 'DELETE' }); await onRefresh(); } catch (err) { onError(err.message); } }
  return <section className="dashboard-panel dashboard-section"><h2>Productos y categorías</h2><div className="dashboard-two-columns"><form className="dashboard-form" onSubmit={saveProduct}><h3>{productId ? 'Editar producto' : 'Crear producto'}</h3><input placeholder="Nombre" value={product.name} onChange={(e) => setProduct({ ...product, name: e.target.value })} required /><textarea placeholder="Descripción" value={product.description} onChange={(e) => setProduct({ ...product, description: e.target.value })} /><input type="number" min="0.01" step="0.01" placeholder="Precio" value={product.price} onChange={(e) => setProduct({ ...product, price: e.target.value })} required /><select value={product.category_id} onChange={(e) => setProduct({ ...product, category_id: e.target.value })} required><option value="">Selecciona una categoría</option>{categories.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><Actions><button type="submit">Guardar producto</button>{productId && <button type="button" onClick={() => { setProductId(null); setProduct(emptyProduct); }}>Cancelar</button>}</Actions></form><form className="dashboard-form" onSubmit={saveCategory}><h3>{categoryId ? 'Editar categoría' : 'Crear categoría'}</h3><input placeholder="Nombre" value={category.name} onChange={(e) => setCategory({ ...category, name: e.target.value })} required /><textarea placeholder="Descripción" value={category.description} onChange={(e) => setCategory({ ...category, description: e.target.value })} /><Actions><button type="submit">Guardar categoría</button>{categoryId && <button type="button" onClick={() => { setCategoryId(null); setCategory(emptyCategory); }}>Cancelar</button>}</Actions></form></div><Table><thead><tr><th>Producto</th><th>Precio</th><th>Categoría</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{products.map((item) => <tr key={item.id}><td>{item.name}</td><td>${item.price}</td><td>{item.category?.name || 'Sin categoría'}</td><td>{item.active ? 'Activo' : 'Inactivo'}</td><td><Actions><button type="button" onClick={() => { setProductId(item.id); setProduct({ name: item.name, description: item.description || '', price: item.price, category_id: item.category_id }); }}>Editar</button>{item.active && <button type="button" onClick={() => remove(`/products/${item.id}`)}>Desactivar</button>}</Actions></td></tr>)}</tbody></Table><Table><thead><tr><th>Categoría</th><th>Descripción</th><th>Acciones</th></tr></thead><tbody>{categories.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.description || 'Sin descripción'}</td><td><Actions><button type="button" onClick={() => { setCategoryId(item.id); setCategory({ name: item.name, description: item.description || '' }); }}>Editar</button><button type="button" onClick={() => remove(`/categories/${item.id}`)}>Eliminar</button></Actions></td></tr>)}</tbody></Table></section>;
}

function IngredientManagement({ ingredients, onRefresh, onError }) {
  const [form, setForm] = useState(emptyIngredient); const [editingId, setEditingId] = useState(null);
  async function save(event) { event.preventDefault(); try { await apiRequest(editingId ? `/ingredients/${editingId}` : '/ingredients', { method: editingId ? 'PUT' : 'POST', body: JSON.stringify({ ...form, current_stock: Number(form.current_stock || 0), minimum_stock: Number(form.minimum_stock || 0) }) }); setForm(emptyIngredient); setEditingId(null); await onRefresh(); } catch (err) { onError(err.message); } }
  async function remove(id) { try { await apiRequest(`/ingredients/${id}`, { method: 'DELETE' }); await onRefresh(); } catch (err) { onError(err.message); } }
  return <section className="dashboard-panel dashboard-section"><h2>Ingredientes</h2><form className="dashboard-form dashboard-form--grid" onSubmit={save}><input placeholder="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><input placeholder="Unidad (gr, ml, unidades)" value={form.unit} onChange={(e) => setForm({ ...form, unit: e.target.value })} required /><input type="number" min="0" step="0.01" placeholder="Stock actual" value={form.current_stock} onChange={(e) => setForm({ ...form, current_stock: e.target.value })} /><input type="number" min="0" step="0.01" placeholder="Stock mínimo" value={form.minimum_stock} onChange={(e) => setForm({ ...form, minimum_stock: e.target.value })} /><Actions><button type="submit">{editingId ? 'Guardar ingrediente' : 'Crear ingrediente'}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(emptyIngredient); }}>Cancelar</button>}</Actions></form><Table><thead><tr><th>Nombre</th><th>Unidad</th><th>Stock actual</th><th>Stock mínimo</th><th>Acciones</th></tr></thead><tbody>{ingredients.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.unit}</td><td className={Number(item.current_stock) <= Number(item.minimum_stock) ? 'stock-low' : ''}>{item.current_stock}</td><td>{item.minimum_stock}</td><td><Actions><button type="button" onClick={() => { setEditingId(item.id); setForm({ name: item.name, unit: item.unit, current_stock: item.current_stock, minimum_stock: item.minimum_stock }); }}>Editar</button><button type="button" onClick={() => remove(item.id)}>Eliminar</button></Actions></td></tr>)}</tbody></Table></section>;
}

function PromotionManagement({ promotions, products, onRefresh, onError }) {
  const [form, setForm] = useState(emptyPromotion); const [editingId, setEditingId] = useState(null);
  async function save(event) { event.preventDefault(); try { await apiRequest(editingId ? `/promotions/${editingId}` : '/promotions', { method: editingId ? 'PUT' : 'POST', body: JSON.stringify({ ...form, product_id: form.product_id ? Number(form.product_id) : null, discount_percentage: Number(form.discount_percentage) }) }); setForm(emptyPromotion); setEditingId(null); await onRefresh(); } catch (err) { onError(err.message); } }
  async function remove(id) { try { await apiRequest(`/promotions/${id}`, { method: 'DELETE' }); await onRefresh(); } catch (err) { onError(err.message); } }
  return <section className="dashboard-panel dashboard-section"><h2>Promociones</h2><form className="dashboard-form dashboard-form--grid" onSubmit={save}><input placeholder="Nombre" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><select value={form.product_id} onChange={(e) => setForm({ ...form, product_id: e.target.value })}><option value="">Todos los productos</option>{products.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input type="number" min="0" max="100" step="0.01" placeholder="Descuento %" value={form.discount_percentage} onChange={(e) => setForm({ ...form, discount_percentage: e.target.value })} required /><input type="date" value={form.start_date} onChange={(e) => setForm({ ...form, start_date: e.target.value })} required /><input type="date" value={form.end_date} onChange={(e) => setForm({ ...form, end_date: e.target.value })} required /><Actions><button type="submit">{editingId ? 'Guardar promoción' : 'Crear promoción'}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(emptyPromotion); }}>Cancelar</button>}</Actions></form><Table><thead><tr><th>Nombre</th><th>Producto</th><th>Descuento</th><th>Vigencia</th><th>Acciones</th></tr></thead><tbody>{promotions.map((item) => <tr key={item.id}><td>{item.name}</td><td>{item.product?.name || 'Todos'}</td><td>{item.discount_percentage}%</td><td>{item.start_date} - {item.end_date}</td><td><Actions><button type="button" onClick={() => { setEditingId(item.id); setForm({ product_id: item.product_id || '', name: item.name, discount_percentage: item.discount_percentage, start_date: item.start_date, end_date: item.end_date }); }}>Editar</button><button type="button" onClick={() => remove(item.id)}>Eliminar</button></Actions></td></tr>)}</tbody></Table></section>;
}

function AdminOrderManagement({ orders, onRefresh, onError }) {
  async function updateStatus(order, status) { try { await apiRequest(`/orders/${order.id}/status`, { method: 'PUT', body: JSON.stringify({ status }) }); await onRefresh(); } catch (err) { onError(err.message); } }
  return <section className="dashboard-panel dashboard-section"><h2>Pedidos e historial</h2><Table><thead><tr><th>Pedido</th><th>Cliente</th><th>Total</th><th>Estado</th><th>Historial</th><th>Actualizar</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td>#{order.id}</td><td>{order.user?.name || order.user?.email || 'Sin cliente'}</td><td>${order.total}</td><td><span className="status">{statusLabels[order.status] || order.status}</span></td><td><details><summary>{order.statusHistory?.length || 0} cambios</summary><ul className="dashboard-history">{order.statusHistory?.map((item) => <li key={item.id}>{item.previous_status ? `${statusLabels[item.previous_status]} -> ` : ''}{statusLabels[item.new_status] || item.new_status}</li>)}</ul></details></td><td>{transitions[order.status]?.length ? <select defaultValue="" onChange={(e) => { if (e.target.value) updateStatus(order, e.target.value); }}><option value="">Seleccionar</option>{transitions[order.status].map((status) => <option value={status} key={status}>{statusLabels[status]}</option>)}</select> : 'Sin cambios'}</td></tr>)}</tbody></Table></section>;
}

function PaymentManagement({ payments }) {
  return <section className="dashboard-panel dashboard-section"><h2>Pagos registrados</h2><Table><thead><tr><th>Pago</th><th>Pedido</th><th>Cliente</th><th>Método</th><th>Monto</th><th>Estado</th><th>Fecha</th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>#{payment.id}</td><td>#{payment.order_id}</td><td>{payment.order?.user?.name || 'Sin cliente'}</td><td>{payment.paymentMethod?.name || 'Sin método'}</td><td>${payment.amount}</td><td>{payment.status}</td><td>{payment.paid_at || 'Sin fecha'}</td></tr>)}</tbody></Table></section>;
}
